### ISSUE TITLE
New company doesn't show up in dropdowns

### ISSUE THREAD

**Issue by bdeleonardis1** [codebase-berkeley/CodeDoor#33]
Because we are now creating companies via ajax, the page doesn't reload. If you try to create a review or an interview after creating a company the new company doesn't appear in the dropdown until you reload.

The fix is pretty simple - via JavaScript add the the company to both dropdowns when it gets created.

**Comment by theandrewchan** [comment]
No longer relevant as we are no longer using fixed dropdowns.
