### ISSUE TITLE
Disallow Zero Transactions

### ISSUE THREAD

**Issue by theandrewchan** [codebase-berkeley/CodeDoor#88]
Don't allow spam of transactions.

Also, maybe set a minimum transaction amt.

**Comment by njaladan** [comment]
Are we enforcing a min limit for coinflip too? I was thinking the minimum for both could be 10 - open to hearing suggestions.

**Comment by theandrewchan** [comment]
Min limit for coin flip is already 100!

**Comment by njaladan** [comment]
set min transaction to 100 as well! hopefully this works out 👍
